meta:
  version: "1.0"
  last_updated: "2025-01-14"
  priority_scheme: "MoSCoW"

users:
  roles: [attending MD, resident] # MUST - Primary users
  settings: [outpatient clinic] # MUST - Start here, expand later
  specialties: [primary care, internal medicine] # MUST - Highest documentation burden
  patient_present_pct: 85
  accessibility: [headset option for hearing impaired providers]

use_cases:
  ranked_tasks:
    - "Ambient scribe → SOAP note" # MUST - Core value prop, saves 5-7 min/visit
    - "Retrieve last 3 labs/vitals" # MUST - Most common chart lookup
    - "Generate ICD-10/CPT codes" # MUST - Revenue critical
    - "Create after-visit summary" # SHOULD - Patient satisfaction
    - "Order labs (read-only preview)" # COULD - Requires deep integration
    - "Send message to team" # COULD - Nice to have
    - "Refill medications" # WON'T - Too risky for v1
    - "Order medications" # WON'T - Liability without full integration
  documentation_mode: hybrid # Ambient during visit, command for corrections
  order_entry: [] # WON'T in v1 - read-only first
  chart_navigation: [labs, vitals, meds, allergies, problem list] # Read-only
  refill_policies: "Not supported in v1"
  coding_scope: [ICD-10, CPT, E&M level]
  avs:
    enabled: true
    languages: [en] # Spanish in v2
  team_messaging:
    enabled: false # v2
    channels: []
  prior_auth:
    enabled: false
    formats: []

ehr:
  vendors: [Epic] # MUST - 60% market share
  integration: [FHIR R4 read-only] # Start safe
  fhir_resources: [Patient, Encounter, Observation, Condition, AllergyIntolerance, MedicationStatement]
  auth: "OAuth2/SMART launch context"
  audit_fields: [userId, patientId, action, timestamp, encounterId]
  fallback_policy: "Cache last successful read for 1hr; graceful degradation"

voice_ux:
  modes: [ambient] # Focus on one mode first
  wake: "push_to_talk" # Safest for PHI
  barge_in: false # v2
  confirmations: "Read-back note sections before save"
  readback_style: "section headers only unless requested"
  multi_party_strategy: "Single mic near provider"
  vocab_strategy: "Deepgram medical model + custom medical terms"
  phi_audio_policy: "Headset only when patient not present"
  timeouts_ms: 10000
  providers:
    asr: "Deepgram Medical"
    tts: "None - text display only for v1"
  ui_surfaces: [web_transcript, status_indicator, edit_pane]

privacy:
  baa: true # MUST have with Deepgram
  retention_days:
    audio: 0 # Delete immediately after processing
    transcripts: 7 # For corrections
    logs: 90 # Audit requirement
  residency: "US-only"
  encryption: "TLS 1.3 transit; AES-256 at rest"
  consent_flow: "Written consent in intake forms"
  rbac: "Provider can see own encounters only"
  model_logging_policy: "No PHI in prompts to Hugging Face"
  redaction: "All PHI redacted before any external API"
  ir_plan: "RTO 4h; RPO 1h; breach notification within 72h"

nlu:
  capability_matrix: "Transcription → Structure → Codes"
  grounding_sources: ["Encounter context only"]
  hallucination_rules: "Template-based generation only"
  entity_schema: "medications, problems, vitals"
  temporal_reasoning: "Today's visit only for v1"
  negation_uncertainty: "Flag for review"
  templates: "SOAP template with prompts"
  output_formats: "JSON → Copy/paste to EHR"
  multilingual: [en]

safety:
  risk_catalog: "Documentation errors only (no orders)"
  double_confirms: "Review before saving any note"
  hard_stops: "None - documentation only"
  display_allergies_problems: true # Context display
  provider_only_mode: "Always on for v1"
  escalation: "Manual editing always available"

performance:
  asr_latency_p95_ms: 500 # Deepgram actual
  wer_target_pct: 5.0 # Medical model capability
  e2e_latency_p95_ms: 3000 # Including AI generation
  availability_slo_pct: 99.5
  offline_capabilities: "Queue for later processing"
  cost_per_user_day_usd: 8.00 # Realistic with current APIs
  telemetry_fields: [time_saved, notes_generated, edits_required]

hardware:
  mics: ["USB headset", "Laptop built-in"]
  room_acoustics: "Standard exam room"
  device_policy: "Provider laptop/tablet"
  form_factors: [web_app]

content:
  note_templates: ["Primary Care SOAP"]
  smart_phrases: [] # v2
  patient_instructions: "Basic template"
  billing_prompts: "E&M level suggestion"

business:
  kpis: ["Documentation time ↓50%", "After-hours ↓30%", "Complete notes in visit"]
  pilot_plan: "5 providers, 4 weeks, A/B days"
  training: "30 min video + practice session"
  support: "Email with 4h response"
  approvals: ["HIPAA officer", "Medical director"]