version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rcm-postgres
    environment:
      POSTGRES_DB: medplum
      POSTGRES_USER: medplum
      POSTGRES_PASSWORD: medplum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medplum"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rcm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Medplum Server (FHIR Backend)
  medplum:
    image: medplum/medplum-server:latest
    container_name: rcm-medplum
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8103:8103"
    environment:
      NODE_ENV: development
      PORT: 8103
      DATABASE_URL: postgres://medplum:medplum@postgres:5432/medplum
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:8103
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8103/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RCM API Server
  api:
    build: ./backend
    container_name: rcm-api
    depends_on:
      medplum:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://medplum:medplum@postgres:5432/medplum
      - REDIS_URL=redis://redis:6379/0
      - MEDPLUM_BASE_URL=http://medplum:8103
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
